# Postgres via Cloud SQL (docs/01-ARCHITECTURE.md §2.2 — [Fixed], relational integrity required).
# Password is generated by Terraform (random_password) and written straight into Secret
# Manager — never appears in .tfvars or any committed file (docs/09-TERRAFORM-IAC.md §4).

resource "random_password" "db_password" {
  length  = 32
  special = false # avoid characters that need extra escaping in connection strings
}

resource "google_sql_database_instance" "this" {
  name             = var.instance_name
  project          = var.project_id
  region           = var.region
  database_version = "POSTGRES_16"

  deletion_protection = var.deletion_protection

  settings {
    tier = var.tier
    # ENTERPRISE (not the newer ENTERPRISE_PLUS, now the GCP default for new instances) is
    # required for shared-core tiers like db-f1-micro — ENTERPRISE_PLUS only supports
    # db-perf-optimized-* tiers, which cost meaningfully more than this dev sizing needs.
    edition = "ENTERPRISE"

    availability_type = var.availability_type

    backup_configuration {
      enabled                        = var.backup_enabled
      point_in_time_recovery_enabled = var.backup_enabled
    }

    # Cloud Run itself always connects via the Cloud SQL Auth Proxy/connector regardless of
    # this setting (docs/08-INFRA-DEPLOYMENT.md §3) — enable_public_ip is only for direct
    # external access (e.g. a local client), gated by authorized_networks below since a
    # public IP alone doesn't open access to anything.
    ip_configuration {
      ipv4_enabled = var.enable_public_ip

      dynamic "authorized_networks" {
        for_each = var.authorized_networks
        content {
          name  = authorized_networks.value.name
          value = authorized_networks.value.cidr
        }
      }
    }
  }
}

resource "google_sql_database" "this" {
  name     = var.database_name
  project  = var.project_id
  instance = google_sql_database_instance.this.name
}

resource "google_sql_user" "this" {
  name     = var.database_user
  project  = var.project_id
  instance = google_sql_database_instance.this.name
  password = random_password.db_password.result
}

resource "google_secret_manager_secret" "db_connection_string" {
  secret_id = "${var.instance_name}-connection-string"
  project   = var.project_id

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "db_connection_string" {
  secret = google_secret_manager_secret.db_connection_string.id
  secret_data = format(
    "postgresql://%s:%s@localhost/%s?host=/cloudsql/%s",
    var.database_user,
    random_password.db_password.result,
    var.database_name,
    google_sql_database_instance.this.connection_name,
  )
}
